name: project_x
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  avatar_glow: ^2.0.2
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_audio_manager: ^0.2.3
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  path_provider: ^2.0.11
  path_provider_ios: ^2.0.11
  speech_to_text: ^5.6.1
  text_to_speech: ^0.2.3
  translator: ^0.1.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
assets:
  - assets/sounds/speech_to_text_listening.m4r
  - assets/sounds/speech_to_text_cancel.m4r
  - assets/sounds/speech_to_text_stop.m4r
